extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317

processors:
  batch:

exporters:
  awsxray:
    region: 'eu-west-1'
  awsemf:
    namespace: 'ADOTMetricNS'
    log_retention: 60
    region: 'eu-west-1'

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [awsxray]
    metrics:
      receivers: [otlp]
      exporters: [awsemf]
  extensions: [health_check]
