name: CI/CD

# Controls when the action will run. Workflow runs a PR is created
# or when a commit is pushed to the PR source branch.
on:
  push:
    branches:
      - 'develop'
      - 'main'
  pull_request:
    branches:
      - 'develop'
      - 'main'

env:
  DOCKER_CLI_EXPERIMENTAL: enabled
  AWS_REGION: "eu-west-1"
  FAST_VERSION: "0.5.6-beta"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::192351105085:role/GithubActionsRole"
          role-session-name: "GitHub_to_AWS_via_FederatedOIDC"
          aws-region: ${{ env.AWS_REGION }}

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/checkout@v4

      - name: Install Fast (Specific Version)
        run: curl -fsSL https://raw.githubusercontent.com/Obornes/install-fast/main/install_fast_linux.sh | bash -s $FAST_VERSION

      - name: Create Fast folder
        run: |
          mkdir -p $HOME/.fast/config
          sed -i -e "s/fast_access_token/${{secrets.TOKEN_FAST_FOR_GITHUB_ACTIONS}}/g" .github/fast.yaml
          cp .github/fast.yaml $HOME/.fast/config/fast.yaml && cat $HOME/.fast/config/fast.yaml

      - name: Install Fast requirements
        run: fast self:install

      - name: Docker Login
        run: fast docker:login_ci

      - name: Run build task
        run: fast app:pack --cache ci --platform "linux/amd64"

      - name: Pushing image
        if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main' || github.base_ref == 'main'
        run: |
          if ! fast app:image:pull ; then
            fast app:release
          else
            echo "::warning ::Error Image Release - Tag already exists"
          fi

      - name: Creating a Github release
        if: github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{secrets.TOKEN_FAST_FOR_GITHUB_ACTIONS}}
        run: |
          fast app:image:tag_base_image
          fast github:release:create 


  deploy:
    if: github.ref == 'refs/heads/develop' || github.base_ref == 'main' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    concurrency:
      group: deployment
    needs:
      - build
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Install Fast (Specific Version)
        run: curl -fsSL https://raw.githubusercontent.com/Obornes/install-fast/main/install_fast_linux.sh | bash -s $FAST_VERSION

      - name: Create Fast folder
        run: |
          mkdir -p $HOME/.fast/config
          sed -i -e "s/fast_access_token/${{secrets.TOKEN_FAST_FOR_GITHUB_ACTIONS}}/g" .github/fast.yaml
          cp .github/fast.yaml $HOME/.fast/config/fast.yaml && cat $HOME/.fast/config/fast.yaml

      - name: Install Fast requirements
        run: fast self:install

      - name: configure aws credentials
        if: github.ref == 'refs/heads/develop'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::192351105085:role/GithubActionsRole"
          role-session-name: "GitHub_to_AWS_via_FederatedOIDC"
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy on SDBX
        if: github.ref == 'refs/heads/develop'
        env:
          GH_TOKEN: ${{secrets.TOKEN_FAST_FOR_GITHUB_ACTIONS}}
        run: |
          fast aws:persist_credentials
          fast app:deploy:apply --env sdbx

